[mouse]
hide_when_typing = true

[window]
startup_mode = "Windowed"

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font"
style = "Light"

[font.italic]
family = "Hack Nerd Font"
style = "Light Italic"

[font.bold]
family = "Hack Nerd Font"
style = "Medium"


# Colors (Gruvbox Material Hard Dark)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
